### ISSUE TITLE
I don't understand in what circumstances I should use ng-include and when I should use ng-inline

### ISSUE THREAD

**Issue by tom10271** [zachsnow/ng-inline#5]
The blog post link has broken.

As title mentioned, how should I decide? And what is the difference between ng-include and ng-inline besides speed?

Thanks for helping

**Comment by zachsnow** [comment]
Thanks for pointing out the busted link; fixed!

You would prefer `ng-inline` for things that might happen in tight loops -- you'll make bootstrapping slower, but linking faster.  Whereas `ng-include` will keep your bootstrap faster, but make your linking slower. Also, `ng-inline` only supports templates that are already in the template cache.
